services:
  frontend:
    build:
      context: ./frontend
      target: build
    command: "npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    command: "uv run fastapi dev main.py --host 0.0.0.0 --forwarded-allow-ips=*"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/.venv
      - /app/__pycache__