#!/usr/bin/env bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $POSTGRES_LOCAL_USER WITH PASSWORD '$POSTGRES_LOCAL_PASSWORD';
	GRANT CONNECT ON DATABASE $POSTGRES_DB TO $POSTGRES_LOCAL_USER;
	ALTER DEFAULT PRIVILEGES
		FOR USER $POSTGRES_USER
		IN SCHEMA public
		GRANT SELECT, INSERT, UPDATE ON TABLES TO $POSTGRES_LOCAL_USER;
EOSQL